dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

networks:
  development:
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    fee: 100000000000000000
    verify: False
  kovan:
    eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
    verify: True